name: "Weekly News Summarizer"

on:
  schedule:
    - cron: '0 13 * * 1'  # Every Monday at 08:00 EST
  workflow_dispatch:  # Allows manual trigger

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run summarizer
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python summarize_articles.py

      - name: Upload database artifact
        uses: actions/upload-artifact@v3
        with:
          name: articles-db
          path: articles.db
